- name: Install apache2
  yum: name=httpd state=present

- name: Start apache2 
  service: name=httpd state=started

- name: allow apache2 to modify files on the shared vagrant folder
  when: ansible_ssh_user == 'vagrant'
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    line="{{ item.line }}"
    state=present
  with_items:
      - { regexp: 'Group apache', line: 'Group vagrant' }
  notify:
    - restart apache
