- name: Install Mysql server
  yum: name={{item}}
  with_items:
    - mysql
    - mysql-server
    - MySQL-python

- name: Start the MySQL service
  action: service name=mysqld state=started

- name: Check if credentials for mysql are already present
  stat: path=/root/.my.cnf
  register: database_configured
  changed_when: False

- name: Copy .my.cnf file with root password credentials
  template: src=root/my.empty.cnf dest=/root/.my.cnf owner=root mode=0600
  when: database_configured.stat.exists == False

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{item}} password=root
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: database_configured.stat.exists == False

- name: Copy .my.cnf file with root password credentials
  template: src=root/my.cnf dest=/root/.my.cnf owner=root mode=0600
  when: database_configured.stat.exists == False

- name: Delete anonymous MySQL server user for $server_hostname
  action: mysql_user user="" host="$server_hostname" state="absent"
  when: database_configured.stat.exists == False

- name: Delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"
  when: database_configured.stat.exists == False

