- name: Create a directory to place the SSL Certificate
  file: path={{nginx_cert_root_path}} state=directory
  register: ssl_cert_path_output

- name: Check if SSL certificete for {{hostname}} was already created
  stat: path="{{ssl_cert_path_output.path}}/{{hostname}}.key"
  register: ssl_path

- name: Create a Self Signed SSL Certificate
  command: "openssl req -subj '/CN={{hostname}}/O={{cert_organization_name}}/OU={{cert_organization_unit}}/ST={{cert_state}}/L={{cert_city}}/C={{cert_country}}' -new -newkey rsa:{{cert_rsa}} -days {{cert_days}} -nodes -x509 -keyout {{ssl_cert_path_output.path}}/{{hostname}}.key -out {{ssl_cert_path_output.path}}/{{hostname}}.crt"
  when: ssl_path.stat.exists == false
