- name: Install git
  yum: name=git

- name: Define git aliases
  copy: src=.gitconfig dest=~
  sudo: no

- name: Configure git to work with proxy
  command: "git config --global {{ item }} {{ proxy }}"
  when: proxy is defined and proxy != "" and proxy != false
  with_items:
    - "http.proxy"
    - "https.proxy"
