- name: Check requirements
  fail: msg="Only centos based box are supported at this moment. You are currently using {{ ansible_os_family }}"
  when: ansible_os_family != "RedHat"

- name: Proxy configurations
  when: proxy is defined and proxy != ""
  include: proxy.yml

- name: Change the hostname
  hostname: name={{ vm_name }}
  register: hostname_set

- name: Set the hostname in the /etc/host
  lineinfile: dest=/etc/hosts line='127.0.0.1 {{ vm_name }}'
  when: hostname_set.changed

- include: git.yml
- include: tools.yml
