- name: Configure Proxy globally
  lineinfile: dest={{ item[0] }} line='{{ item[1] }}={{ proxy }}' state=present
  with_items:
    - ["/etc/wgetrc", "/etc/environment", "/etc/bash.bashrc"]
    - [ "http_proxy", "https_proxy", "ftp_proxy" ]

- name: Configure Proxy for apt
  lineinfile:  dest=/etc/apt/apt.conf line='{{ item }}' create=yes
  with_items:
  - 'Acquire::http::proxy "{{ proxy }}";'
  - 'Acquire::ftp::proxy "{{ proxy }}";'
  - 'Acquire::https::proxy "{{ proxy }}";'
