- name: Configure Proxy globally
  lineinfile: dest={{ item }} line='http_proxy={{ proxy }}'
  with_items:
    - /etc/wgetrc
    - /etc/environment

    - name: Configure Proxy for apt
  lineinfile:  dest=/etc/apt/apt.conf line='{{ item }}' create=yes
  with_items:
  - 'Acquire::http::proxy "{{ proxy }}";'
  - 'Acquire::ftp::proxy "{{ proxy }}";'
  - 'Acquire::https::proxy "{{ proxy }}";'
