- name: Configure Proxy globally
  lineinfile: dest={{ item[0] }} line='{{ item[1] }}={{ proxy }}' state=present
  register: proxy_configured
  with_nested:
    - ["/etc/wgetrc", "/etc/environment", "/etc/bash.bashrc"]
    - [ "http_proxy", "https_proxy", "ftp_proxy" ]

- name: Configure Proxy for apt
  lineinfile:  dest=/etc/apt/apt.conf line='{{ item }}' create=yes
  with_items:
  - 'Acquire::http::proxy "{{ proxy }}";'
  - 'Acquire::ftp::proxy "{{ proxy }}";'
  - 'Acquire::https::proxy "{{ proxy }}";'

- name: Restart is required
  fail: msg="Proxy settings has changed, please log out and login again. Then run /provision/run to continue provision the machine"
  when: proxy_configured.changed
