- name: Install PHPMyadmin
  apt: name=phpmyadmin

- name: Configure PHPMyadmin for nginx
  when: vendors.webserver == 'nginx'
  copy: src=phpmyadmin.nginx.conf dest=/etc/nginx/sites-enabled/phpmyadmin.nginx.conf
  notify: restart nginx
