- name: Install PHPMyadmin
  yum: name=phpmyadmin

- name: Configure PHPMyadmin for nginx
  when: vendors.webserver == 'nginx'
  copy: src=phpmyadmin.nginx.conf dest=/etc/nginx/conf.d/phpmyadmin.nginx.conf
  notify: restart nginx

- name: Configure PHPMyadmin for apache
  when: vendors.webserver == 'apache'
  copy: src=phpmyadmin.apache.conf dest=/etc/apache2/sites-enabled/phpmyadmin.apache.conf
  notify: restart apache

- name: Open port 81 for apache server
  when: vendors.webserver == "apache"
  lineinfile:
      dest=/etc/apache2/ports.conf
      insertafter="Listen 80"
      line="Listen 81"
      state=present
  notify:
    - restart apache


