- include: php54.yml
  when: version == "5.4"

- include: php55.yml
  when: version == "5.5"

- include: php56.yml
  when: version == "5.6"

- name: Ensure PHP is enabled for apache
  when: vendors.webserver == "apache"
  lineinfile:
      dest=/etc/apache2/mods-enabled/mime.conf
      insertbefore="</IfModule>"
      line="{{ item.line }}"
      state=present
  with_items:
      - { line: "AddType  application/x-httpd-php         .php"  }
      - { line: "AddType  application/x-httpd-php-source  .phps" }
  notify:
    - restart apache

- name: Enable PHP module for apache
  when: vendors.webserver == "apache"
  apache2_module: state=present name=php5

# Configure PHP for development
- include: php-dev.yml
  when: env == "dev"

- name: Config timezone for PHP and restart apache
  action: ini_file dest=/etc/php5/apache2/conf.d/20-timezone.ini section=Date option=date.timezone value="{{ php_date_timezone }}" mode=0600
  when: vendors.webserver == "apache"
  notify:
    - restart apache

- name: Config timezone for PHP and restart nginx
  action: ini_file dest=/etc/php5/fpm/conf.d/20-timezone.ini section=Date option=date.timezone value="{{ php_date_timezone }}" mode=0600
  when: vendors.webserver == "nginx"
  notify:
    - restart nginx

- name: Config timezone for PHP for cli
  action: ini_file dest=/etc/php5/cli/conf.d/20-timezone.ini section=Date option=date.timezone value="{{ php_date_timezone }}" mode=0600
