- include: php54.yml
  when: version == "5.4"

- include: php55.yml
  when: version == "5.5"

- include: php56.yml
  when: version == "5.6"

- name: Allow nginx to modify files on the shared vagrant folder
  when: ansible_ssh_user == 'vagrant' and vendors.webserver == 'nginx'
  lineinfile:
      dest=/etc/php-fpm.d/www.conf
      regexp="{{ item.regexp }}"
      line="{{ item.line }}"
      backrefs=yes
      state=present
  with_items:
      - { regexp: 'group = apache', line: 'group = vagrant' }
  notify:
    - restart fpm

- name: Ensure PHP is enabled for apache
  when: vendors.webserver == "apache"
  lineinfile:
      dest=/etc/apache2/mods-enabled/mime.conf
      insertbefore="</IfModule>"
      line="{{ item.line }}"
      state=present
  with_items:
      - { line: "AddType  application/x-httpd-php         .php"  }
      - { line: "AddType  application/x-httpd-php-source  .phps" }
  notify:
    - restart apache

- name: Enable PHP module for apache
  when: vendors.webserver == "apache"
  apache2_module: state=present name=php5

# Configure PHP for development
- include: php-dev.yml
  when: env == "dev"

- name: Configure timezone for PHP
  lineinfile:
      dest=/etc/php.ini
      regexp="{{ item.regexp }}"
      line="{{ item.line }}"
      backrefs=yes
      state=present
  with_items:
      - { regexp: ';date.timezone =', line: 'date.timezone = "America/Argentina/Buenos_Aires"' }
  register: timezone_changed

- name: Restart server
  debug: msg="Restart webserver"
  when: timezone_changed.changed and vendors.webserver == 'nginx'
  notify:
    - restart fpm

- name: Restart server
  debug: msg="Restart webserver"
  when: timezone_changed.changed and vendors.webserver == 'apache'
  notify:
    - restart httpd
