- name: Display errors for PHP on nginx
  when: vendors.webserver == 'nginx'
  lineinfile:
      dest=/etc/php.ini
      regexp='display_errors = Off'
      line='display_errors = On'
      backrefs=yes
      state=present
  notify:
    - restart fpm

- name: Display errors for PHP on apache
  when: vendors.webserver == 'apache'
  lineinfile:
      dest=/etc/php.ini
      regexp='display_errors = Off'
      line='display_errors = On'
      backrefs=yes
      state=present
  notify:
    - restart httpd


- name: Display errors for PHP on nginx
  when: vendors.webserver == 'nginx'
  lineinfile:
      dest=/etc/php-fpm.d/www.conf
      regexp="{{ item.regexp }}"
      line="{{ item.line }}"
      backrefs=yes
      state=present
  with_items:
      - { regexp: ';php_flag\[display_errors\] = off', line: 'php_flag[display_errors] = on' }
      - { regexp: ';catch_workers_output = yes', line: 'catch_workers_output = yes' }
  notify:
    - restart fpm
