- name: Check if nginx is installed
  shell: whereis nginx
  register: nginx_path
  changed_when: False

- name: Check if apache is installed
  shell: whereis apache2
  register: apache_path
  changed_when: False

- name: Display errors for PHP on nginx
  when: nginx_path.stdout != "nginx:"
  lineinfile:
      dest=/etc/php5/fpm/php.ini
      regexp='display_errors = Off'
      line='display_errors = On'
      backrefs=yes
      state=present
  notify:
    - restart fpm

- name: Display errors for PHP on nginx
  when: nginx_path.stdout != "nginx:"
  lineinfile:
      dest=/etc/php5/fpm/pool.d/www.conf
      regexp="{{ item.regexp }}"
      line="{{ item.line }}"
      backrefs=yes
      state=present
  with_items:
      - { regexp: ';php_flag\[display_errors\] = off', line: 'php_flag[display_errors] = on' }
      - { regexp: ';catch_workers_output = yes', line: 'catch_workers_output = yes' }
  notify:
    - restart fpm
