- name: Add PHP 5.6 repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install PHP packages
  yum: name={{item}}
  with_items:
    - php56w
    - php56w-common
    - php56w-gd

- name: Install specific fpm PHP packages
  yum: name={{item}}
  when: vendors.webserver == 'nginx'
  with_items:
    - php56w-fpm
