- name: Add PHP 5.4 repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install PHP packages
  yum: name={{item}}
  with_items:
    - php
    - php-cli
    - php-gd
    - php-pecl-apcu

- name: Install specific fpm PHP packages
  yum: name={{item}}
  when: vendors.webserver == 'nginx'
  with_items:
    - php-fpm
