version: "7.34"
folder_name: drupal
drush_options: ""
admin_user: "admin"
admin_pass: "admin"
install: "yes"
profile: "standard"
site_name: "Drupal"
extra_install_params: ""
webserver: false
debug: false
