- name: Check if composer is Installed
  shell: whereis composer
  register: composer_path
  changed_when: False

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php
  when: composer_path.stdout == 'composer:'
  register: composer_downloaded
  args:
    chdir: /tmp

- name: Make composer globally available.
  shell: mv composer.phar /usr/local/bin/composer
  when: composer_downloaded.changed
  args:
    chdir: /tmp

