- hosts: all
  sudo: True
  remote_user: vagrant
  vars:
    vm_name: testvm
    vendors:
      webserver: apache
      database: mariadb

  roles:
    - { role: common }
    - { role: webserver }
    - { role: php, version: "5.6", env: dev }
    - { role: dev/tools }
    - { role: dev/composer }
    - { role: dev/drush }
    - { role: database}
    - { role: dev/phpmyadmin }

    - { role: apps/drupal,
            hostname: "drupal7.mysite.com",
            root_dir: "/vagrant/drupal7",
            drupal_version: "7.34",
            drupal_install: "yes",
            drupal_db_url: "mysql://root:root@localhost/drupal7"
      }

    - { role: apps/drupal,
            hostname: "drupal8.mysite.com",
            root_dir: "/vagrant/drupal8",
            drupal_version: "8.0.x-dev",
            drupal_install: "yes",
            drupal_db_url: "mysql://root:root@localhost/drupal8",
            debug: true
      }
    - { role: dev/wpcli }

