- hosts: all
  sudo: True
  remote_user: vagrant
  vars:
    vm_name: testvm
    vendors:
      webserver: apache # alternatives: nginx
      database: mysql   # alternatives: mariadb

  roles:
    - { role: common }
    - { role: webserver }
    - { role: php, version: "5.6", env: dev }
    - { role: dev/tools }
    - { role: dev/composer }
    - { role: dev/drush }
    - { role: database}
    - { role: dev/phpmyadmin }

    - { role: dev/ssl_cert, hostname: 'drupal7.example.com' }
    - { role: apps/drupal,
            hostname: "drupal7.example.com",
            root_dir: "/vagrant/drupal7",
            version: "7.37",
            install: "yes",
            db_url: "mysql://root:root@localhost/drupal7",
            https: "yes",

      }

    - { role: dev/wpcli }

    - { role: dev/ssl_cert, hostname: 'wp.example.com' }
    - { role: apps/wordpress,
           hostname: "wp.example.com",
           root_dir: "/vagrant/wp",
           database_name: "wp",
           database_user: "root",
           database_pass: "root",
           https: "yes",

      }

    - { role: dev/laravel_installer }
    - { role: dev/ssl_cert, hostname: 'laravel.example.com' }
    - { role: apps/laravel,
           hostname: "laravel.example.com",
           root_dir: "/vagrant/laravel",
           database_name: "laravel",
           database_user: "lara1",
           database_pass: "lara2",
           https: "yes",
      }

    - { role: dev/ssl_cert, hostname: 'drupal8.example.com' }
    - { role: apps/drupal,
            hostname: "drupal8.example.com",
            root_dir: "/vagrant/drupal8",
            version: "8.0.0-beta10",
            install: "yes",
            db_url: "mysql://root:root@localhost/drupal8",
            https: "no",

      }
