#! /bin/bash

# If you are using a proxy server, uncomment the next line
# PROXY="http://username:password@host:3128"

# Some firewalls block the git:// protocol, you can change it here (usually to https://)
GIT_PROTOCOL="git://"

if [ -n "${PROXY+1}" ]; then
  export {http,https,ftp}_proxy=$PROXY
fi

if ! hash ansible-playbook 2>/dev/null; then
    # Install git
    sudo -E apt-get update
    sudo -E apt-get upgrade -y
    sudo -E apt-get install git-core python python-dev -y

    # Install easy_install
    wget http://peak.telecommunity.com/dist/ez_setup.py -O /tmp/ez_setup.py
    sudo -E python /tmp/ez_setup.py
    sudo -E easy_install pip
    rm ez_setup.py

    # Install PIP
    sudo -E easy_install pip

    # Install Ansible dependencies
    sudo -E pip install paramiko PyYAML Jinja2 httplib2

    # Install Ansible
    sudo -E pip install ansible
else
    echo "Ansible is already installed"
fi

PROVISIONING_DIR=$(cd $(dirname "$0"); pwd)

if [ -z ${PROXY+x} ]; then
  ansible-playbook -i 'localhost,' $PROVISIONING_DIR/ansible.yml --connection=local --extra-vars "git_protocol=$GIT_PROTOCOL"
else
  ansible-playbook -i 'localhost,' $PROVISIONING_DIR/ansible.yml --connection=local --extra-vars "proxy=$PROXY git_protocol=$GIT_PROTOCOL"
fi
