#! /bin/bash

# If you are using a proxy server, uncomment the next line
# export {http,https,ftp}_proxy='http://username:password@host:3128'

if ! hash ansible-playbook 2>/dev/null; then
    # Install git
    sudo -E apt-get update
    sudo -E apt-get upgrade -y
    sudo -E apt-get install git-core python python-dev -y

    # Install easy_install
    wget http://peak.telecommunity.com/dist/ez_setup.py -O /tmp/ez_setup.py
    sudo -E python /tmp/ez_setup.py
    sudo -E easy_install pip
    rm ez_setup.py

    # Install PIP
    sudo -E easy_install pip

    # Install Ansible dependencies
    sudo -E pip install paramiko PyYAML Jinja2 httplib2

    # Install Ansible
    sudo -E pip install ansible
else
    echo "Ansible is already installed"
fi

PROVISIONING_DIR=$(cd $(dirname "$0"); pwd)
ansible-playbook -i 'localhost,' $PROVISIONING_DIR/ansible.yml --connection=local
