- hosts: all
  sudo: True
  remote_user: vagrant
  vars:
    vm_name: testvm
    vendors:
      webserver: apache
      database: mariadb

  roles:
    - { role: common }
    - { role: webserver }
    - { role: php, version: "5.6", env: dev }
    - { role: dev/tools }
    - { role: database}
    - { role: dev/phpmyadmin }
    - { role: dev/composer }
    - { role: dev/wpcli }

    - { role: apps/wordpress,
           hostname: "wp.example.com",
           root_dir: "/vagrant/wp",
           database_name: "wp",
           database_user: "root",
           database_pass: "root",
       }
